mode: rule
log-level: info
allow-lan: false
mixed-port: 7890
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 8.8.8.8
proxies:
  - name: my-server-1
    type: ss
    server: your-server-1.example.com # CHANGE_ME: your real server address
    port: 8388
    cipher: aes-128-gcm
    password: "CHANGE_ME" # CHANGE_ME: your real password
  - name: my-server-2
    type: trojan
    server: your-server-2.example.com # CHANGE_ME: your real server address
    port: 443
    password: "CHANGE_ME" # CHANGE_ME: your real password
